/**
 * Buff 池配置
 * 所有 Buff 的定义，方便调整数值平衡
 */

// Buff 品质
export const BUFF_QUALITY = {
  WHITE: { id: 'white', name: '普通', color: '#ffffff', border: '#cccccc', minLevel: 1 },
  BLUE: { id: 'blue', name: '稀有', color: '#4488ff', border: '#2266dd', minLevel: 5 },
  PURPLE: { id: 'purple', name: '史诗', color: '#aa44ff', border: '#8822dd', minLevel: 10 },
  GOLD: { id: 'gold', name: '传说', color: '#ffcc00', border: '#ddaa00', minLevel: 15 },
};

// 品质概率分布
export const QUALITY_RATES = [
  { maxLevel: 4,  rates: { white: 1.0, blue: 0, purple: 0, gold: 0 } },
  { maxLevel: 9,  rates: { white: 0.75, blue: 0.25, purple: 0, gold: 0 } },
  { maxLevel: 14, rates: { white: 0.55, blue: 0.35, purple: 0.10, gold: 0 } },
  { maxLevel: 99, rates: { white: 0.45, blue: 0.35, purple: 0.15, gold: 0.05 } },
];

// Buff 系别
export const BUFF_SCHOOL = {
  WEAPON: { id: 'weapon', name: '武器系', color: '#ff4444', icon: '🗡️' },
  ELEMENT: { id: 'element', name: '元素系', color: '#4488ff', icon: '🔥' },
  SURVIVAL: { id: 'survival', name: '生存系', color: '#44cc44', icon: '🛡️' },
  CONTROL: { id: 'control', name: '控制系', color: '#ffcc00', icon: '⚡' },
};

// 关联关系（用于三选一关联槽）
export const SCHOOL_ASSOCIATIONS = [
  ['WEAPON', 'ELEMENT'],
  ['SURVIVAL', 'CONTROL'],
  ['WEAPON', 'SURVIVAL'],
];

// 完整 Buff 池
export const BUFF_POOL = [
  // === 武器系 ===
  {
    id: 'sword_count',
    name: '剑数+1',
    school: 'WEAPON',
    quality: 'white',
    description: '旋转剑数量 +1',
    effect: { stat: 'swordCount', value: 1, type: 'add' },
    stackable: true,
    maxStacks: 7,
  },
  {
    id: 'sword_length',
    name: '剑刃强化',
    school: 'WEAPON',
    quality: 'white',
    description: '剑刃长度+6，命中范围+3',
    effect: { stat: 'swordLength', value: 6, type: 'add' },
    stackable: true,
    maxStacks: 8,
  },
  {
    id: 'rotation_speed',
    name: '旋转加速',
    school: 'WEAPON',
    quality: 'white',
    description: '旋转速度 +15°/s',
    effect: { stat: 'swordRotationSpeed', value: 15, type: 'add' },
    stackable: true,
    maxStacks: 12,
  },
  {
    id: 'attack_range',
    name: '攻击范围UP',
    school: 'WEAPON',
    quality: 'white',
    description: '旋转半径 +20px',
    effect: { stat: 'swordRadius', value: 20, type: 'add' },
    stackable: true,
    maxStacks: 6,
  },
  {
    id: 'damage_up',
    name: '伤害强化',
    school: 'WEAPON',
    quality: 'white',
    description: '基础伤害 +5',
    effect: { stat: 'swordDamage', value: 5, type: 'add' },
    stackable: true,
    maxStacks: 99,
  },
  {
    id: 'crit_chance',
    name: '暴击率UP',
    school: 'WEAPON',
    quality: 'blue',
    description: '15% 概率造成2倍伤害',
    effect: { stat: 'critChance', value: 0.15, type: 'add' },
    stackable: true,
    maxStacks: 4,
  },
  {
    id: 'multi_target',
    name: '多重打击',
    school: 'WEAPON',
    quality: 'blue',
    description: '每把剑可同时命中+1个目标',
    effect: { stat: 'multiTarget', value: 1, type: 'add' },
    stackable: true,
    maxStacks: 3,
  },
  {
    id: 'sharp_blade',
    name: '锋利剑刃',
    school: 'WEAPON',
    quality: 'purple',
    description: '伤害+10，无视20%防御',
    effect: { stat: 'swordDamage', value: 10, type: 'add', armorPen: 0.2 },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },

  // === 元素系 ===
  {
    id: 'fire_enchant',
    name: '火焰附魔',
    school: 'ELEMENT',
    quality: 'white',
    description: '命中附加灼烧(3秒内每秒3点伤害)',
    effect: { type: 'enchant', element: 'fire' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'frost_enchant',
    name: '冰霜附魔',
    school: 'ELEMENT',
    quality: 'white',
    description: '命中附加减速30%，持续2秒',
    effect: { type: 'enchant', element: 'frost' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'lightning_enchant',
    name: '雷电附魔',
    school: 'ELEMENT',
    quality: 'blue',
    description: '命中触发连锁闪电(弹跳3目标，50%伤害)',
    effect: { type: 'enchant', element: 'lightning' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'poison_enchant',
    name: '毒液附魔',
    school: 'ELEMENT',
    quality: 'blue',
    description: '命中附加中毒(6秒内每秒2点，可叠5层)',
    effect: { type: 'enchant', element: 'poison' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'element_mastery',
    name: '元素精通',
    school: 'ELEMENT',
    quality: 'purple',
    description: '元素效果持续时间+50%',
    effect: { stat: 'elementMastery', value: 0.5, type: 'add' },
    stackable: true,
    maxStacks: 3,
  },

  // === 生存系 ===
  {
    id: 'hp_up',
    name: '生命上限UP',
    school: 'SURVIVAL',
    quality: 'white',
    description: 'HP上限 +25',
    effect: { stat: 'maxHp', value: 25, type: 'add' },
    stackable: true,
    maxStacks: 16,
  },
  {
    id: 'dodge_up',
    name: '闪避率UP',
    school: 'SURVIVAL',
    quality: 'white',
    description: '闪避率 +5%',
    effect: { stat: 'dodgeChance', value: 0.05, type: 'add' },
    stackable: true,
    maxStacks: 14,
  },
  {
    id: 'hp_regen',
    name: '生命恢复',
    school: 'SURVIVAL',
    quality: 'white',
    description: '每5秒恢复 3 HP',
    effect: { stat: 'hpRegen', value: 3, type: 'add' },
    stackable: true,
    maxStacks: 5,
  },
  {
    id: 'lifesteal',
    name: '吸血',
    school: 'SURVIVAL',
    quality: 'blue',
    description: '造成伤害的3%转化为HP',
    effect: { stat: 'lifesteal', value: 0.03, type: 'add' },
    stackable: true,
    maxStacks: 5,
  },
  {
    id: 'shield_gen',
    name: '护盾生成',
    school: 'SURVIVAL',
    quality: 'blue',
    description: '每15秒获得一个吸收15伤害的护盾',
    effect: { stat: 'shieldGen', value: 15, type: 'add' },
    stackable: true,
    maxStacks: 3,
  },
  {
    id: 'steel_will',
    name: '钢铁意志',
    school: 'SURVIVAL',
    quality: 'purple',
    description: '受到伤害-20%，HP<30%时翻倍',
    effect: { stat: 'damageReduction', value: 0.2, type: 'set' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'revive',
    name: '复活',
    school: 'SURVIVAL',
    quality: 'gold',
    description: '死亡时恢复50% HP，整局仅1次',
    effect: { stat: 'hasRevive', value: 1, type: 'set' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },

  // === 控制系 ===
  {
    id: 'knockback',
    name: '击退',
    school: 'CONTROL',
    quality: 'white',
    description: '命中击退怪物50px',
    effect: { stat: 'knockback', value: 50, type: 'set' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'knockback_plus',
    name: '击退强化',
    school: 'CONTROL',
    quality: 'blue',
    description: '击退距离+40px，附带0.3s眩晕',
    effect: { stat: 'knockbackBonus', value: 40, type: 'add' },
    requires: 'knockback',
    stackable: true,
    maxStacks: 3,
  },
  {
    id: 'gravity_field',
    name: '引力场',
    school: 'CONTROL',
    quality: 'blue',
    description: '旋转剑范围内怪物被缓慢拉向圆心',
    effect: { stat: 'hasGravity', value: 1, type: 'set' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'slow_aura',
    name: '定身光环',
    school: 'CONTROL',
    quality: 'purple',
    description: '角色周围60px内怪物移速-40%',
    effect: { stat: 'hasSlowAura', value: 1, type: 'set' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
  {
    id: 'execute',
    name: '斩杀',
    school: 'CONTROL',
    quality: 'gold',
    description: '对HP低于15%的怪物直接击杀',
    effect: { stat: 'hasExecute', value: 1, type: 'set' },
    stackable: false,
    maxStacks: 1,
    unique: true,
  },
];
