/**
 * 道具掉落配置
 */

export const ITEM_TYPES = {
  EXP_GEM: {
    id: 'exp_gem',
    name: '经验宝石',
    color: '#4488ff',
    glowColor: 'rgba(68,136,255,0.4)',
    radius: 8,
    shape: 'circle',
    lifetime: 30,
    blinkTime: 5,
  },
  HP_POTION: {
    id: 'hp_potion',
    name: '生命恢复',
    color: '#44cc44',
    glowColor: 'rgba(68,204,68,0.4)',
    radius: 10,
    shape: 'cross',
    lifetime: 30,
    blinkTime: 5,
    healAmount: 15,
    dropRate: 0.30,
    dropFrom: ['special'],
  },
  ATK_UP: {
    id: 'atk_up',
    name: '攻击力UP',
    color: '#ff4444',
    glowColor: 'rgba(255,68,68,0.4)',
    radius: 10,
    shape: 'diamond',
    lifetime: 20,
    blinkTime: 5,
    duration: 8,
    multiplier: 1.5,
    dropRate: 0.15,
    dropFrom: ['special'],
  },
  SPD_UP: {
    id: 'spd_up',
    name: '移速UP',
    color: '#ddcc22',
    glowColor: 'rgba(221,204,34,0.4)',
    radius: 10,
    shape: 'triangle',
    lifetime: 20,
    blinkTime: 5,
    duration: 8,
    multiplier: 1.3,
    dropRate: 0.15,
    dropFrom: ['special'],
  },
  SWORD_PLUS: {
    id: 'sword_plus',
    name: '剑数+1',
    color: '#ffffff',
    glowColor: 'rgba(255,255,255,0.4)',
    radius: 10,
    shape: 'sword',
    lifetime: 20,
    blinkTime: 5,
    duration: 10,
    maxStacks: 3,
    dropRate: 0.10,
    dropFrom: ['tank'],
  },
  SHIELD: {
    id: 'shield',
    name: '护盾',
    color: '#44cccc',
    glowColor: 'rgba(68,204,204,0.4)',
    radius: 10,
    shape: 'hexagon',
    lifetime: 25,
    blinkTime: 5,
    duration: 15,
    dropRate: 0.20,
    dropFrom: ['bomber'],
  },
};
